FROM ghcr.io/cyber-dojo-languages/gcc:064b8d0
LABEL maintainer=jon@jaggersoft.com

ENV DEBIAN_FRONTEND=noninteractive

COPY install.sh .
RUN ./install.sh && rm ./install.sh

COPY red_amber_green.rb /usr/local/bin
